// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/chatroom.proto

package gateway

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	chatroom "gitlab.srgow.com/warehouse/proto/chatroom"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageReceiveRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ConsumeMessageIDs    []string `protobuf:"bytes,2,rep,name=consumeMessageIDs,proto3" json:"consumeMessageIDs,omitempty"`
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReceiveRequest) Reset()         { *m = MessageReceiveRequest{} }
func (m *MessageReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*MessageReceiveRequest) ProtoMessage()    {}
func (*MessageReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaa1431732d07e9, []int{0}
}

func (m *MessageReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReceiveRequest.Unmarshal(m, b)
}
func (m *MessageReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReceiveRequest.Marshal(b, m, deterministic)
}
func (m *MessageReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReceiveRequest.Merge(m, src)
}
func (m *MessageReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_MessageReceiveRequest.Size(m)
}
func (m *MessageReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReceiveRequest proto.InternalMessageInfo

func (m *MessageReceiveRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MessageReceiveRequest) GetConsumeMessageIDs() []string {
	if m != nil {
		return m.ConsumeMessageIDs
	}
	return nil
}

func (m *MessageReceiveRequest) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type SendMessageRequest struct {
	Token                string                        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Request              *chatroom.SendMessagesRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaa1431732d07e9, []int{1}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SendMessageRequest) GetRequest() *chatroom.SendMessagesRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type GetMemberRequest struct {
	Token                string                     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Request              *chatroom.GetMemberRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetMemberRequest) Reset()         { *m = GetMemberRequest{} }
func (m *GetMemberRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemberRequest) ProtoMessage()    {}
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaa1431732d07e9, []int{2}
}

func (m *GetMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberRequest.Unmarshal(m, b)
}
func (m *GetMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberRequest.Marshal(b, m, deterministic)
}
func (m *GetMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberRequest.Merge(m, src)
}
func (m *GetMemberRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemberRequest.Size(m)
}
func (m *GetMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberRequest proto.InternalMessageInfo

func (m *GetMemberRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetMemberRequest) GetRequest() *chatroom.GetMemberRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type AvailableRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableRequest) Reset()         { *m = AvailableRequest{} }
func (m *AvailableRequest) String() string { return proto.CompactTextString(m) }
func (*AvailableRequest) ProtoMessage()    {}
func (*AvailableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaa1431732d07e9, []int{3}
}

func (m *AvailableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableRequest.Unmarshal(m, b)
}
func (m *AvailableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableRequest.Marshal(b, m, deterministic)
}
func (m *AvailableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableRequest.Merge(m, src)
}
func (m *AvailableRequest) XXX_Size() int {
	return xxx_messageInfo_AvailableRequest.Size(m)
}
func (m *AvailableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableRequest proto.InternalMessageInfo

func (m *AvailableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageReceiveRequest)(nil), "gateway.MessageReceiveRequest")
	proto.RegisterType((*SendMessageRequest)(nil), "gateway.SendMessageRequest")
	proto.RegisterType((*GetMemberRequest)(nil), "gateway.GetMemberRequest")
	proto.RegisterType((*AvailableRequest)(nil), "gateway.AvailableRequest")
}

func init() { proto.RegisterFile("gateway/chatroom.proto", fileDescriptor_fcaa1431732d07e9) }

var fileDescriptor_fcaa1431732d07e9 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x8e, 0xda, 0x30,
	0x10, 0xc7, 0x15, 0x3e, 0x9b, 0x41, 0xaa, 0x52, 0x53, 0x20, 0x75, 0xd5, 0x0a, 0x71, 0xca, 0xa1,
	0x0a, 0x52, 0x5a, 0xa9, 0x97, 0x1e, 0xfa, 0x25, 0xad, 0x58, 0xc1, 0xc5, 0xbb, 0xe7, 0x95, 0x4c,
	0xd6, 0x0a, 0xd1, 0x92, 0x98, 0x8d, 0x0d, 0x88, 0xa7, 0xd8, 0x77, 0xd9, 0x27, 0x5c, 0x11, 0x3b,
	0x76, 0x04, 0x88, 0x53, 0xe4, 0x99, 0xff, 0xfc, 0xfe, 0x9e, 0xc9, 0x18, 0x86, 0x09, 0x95, 0x6c,
	0x4f, 0x0f, 0xd3, 0x78, 0x45, 0x65, 0xc1, 0x79, 0x16, 0x6e, 0x0a, 0x2e, 0x39, 0xea, 0xea, 0x38,
	0xee, 0xc7, 0x3c, 0xcb, 0x78, 0x3e, 0x55, 0x1f, 0x95, 0xc5, 0x83, 0x4a, 0x3d, 0xcd, 0x58, 0xb6,
	0x64, 0x85, 0x0e, 0xf7, 0x4d, 0xd8, 0x92, 0xf0, 0xc8, 0x06, 0x59, 0xcc, 0xd2, 0x5d, 0xa5, 0x9e,
	0xec, 0x61, 0xb0, 0x60, 0x42, 0xd0, 0x84, 0x11, 0x95, 0x20, 0xec, 0x79, 0xcb, 0x84, 0x44, 0x1f,
	0xa1, 0x2d, 0xf9, 0x13, 0xcb, 0x7d, 0x67, 0xec, 0x04, 0x2e, 0x51, 0x07, 0xf4, 0x0d, 0x3e, 0xc4,
	0x3c, 0x17, 0xdb, 0x8c, 0xe9, 0xaa, 0xd9, 0x7f, 0xe1, 0x37, 0xc6, 0xcd, 0xc0, 0x25, 0xe7, 0x09,
	0x84, 0xe1, 0x5d, 0x4c, 0x37, 0x34, 0x4e, 0xe5, 0xc1, 0x6f, 0x8e, 0x9d, 0xa0, 0x4d, 0xcc, 0x79,
	0x12, 0x03, 0xba, 0x63, 0xf9, 0xa3, 0x31, 0xbf, 0xe6, 0xfa, 0x13, 0xba, 0x85, 0x12, 0x94, 0x98,
	0x5e, 0xf4, 0x25, 0x34, 0x93, 0xaa, 0x41, 0x84, 0xa6, 0x90, 0x4a, 0x3d, 0x79, 0x00, 0xef, 0x86,
	0xc9, 0x45, 0x39, 0x9e, 0xeb, 0x16, 0x3f, 0xac, 0x45, 0xa3, 0xb4, 0xc0, 0xd6, 0xe2, 0x14, 0x61,
	0xf9, 0x01, 0x78, 0x7f, 0x76, 0x34, 0x5d, 0xd3, 0xe5, 0xfa, 0x7a, 0x0b, 0xd1, 0xab, 0x03, 0x1d,
	0x05, 0x41, 0x11, 0xb4, 0xe7, 0x3c, 0x49, 0x73, 0xe4, 0x59, 0x0b, 0x95, 0xc2, 0x23, 0x1b, 0x29,
	0x25, 0x84, 0x89, 0x0d, 0xcf, 0x05, 0x43, 0x11, 0x74, 0xe6, 0x3c, 0xe1, 0x5b, 0x89, 0x86, 0x56,
	0x72, 0x7f, 0x24, 0x6b, 0x5b, 0xec, 0x85, 0x7a, 0x39, 0x4c, 0xcd, 0x6f, 0x70, 0xcd, 0xcd, 0xd1,
	0xa7, 0x50, 0xef, 0xd2, 0x59, 0x37, 0xd8, 0x3f, 0xbd, 0x46, 0x45, 0x88, 0x6e, 0xa1, 0x45, 0x38,
	0xcf, 0xd0, 0x5f, 0x70, 0x4d, 0x9b, 0x35, 0xd2, 0x69, 0xeb, 0xb8, 0x36, 0xb3, 0x63, 0xdd, 0x3c,
	0x15, 0xd2, 0xb0, 0x5e, 0x1c, 0x68, 0xfd, 0x5b, 0x51, 0x89, 0x7e, 0x41, 0xaf, 0xf6, 0xcf, 0xd0,
	0x67, 0x83, 0x3b, 0x5f, 0x87, 0x0b, 0x4d, 0xcd, 0xe0, 0xbd, 0x5e, 0xd4, 0x0a, 0xf0, 0xd5, 0x00,
	0x2e, 0x2e, 0xf2, 0x71, 0xa6, 0x8a, 0x61, 0xd2, 0x0a, 0xb5, 0xec, 0x94, 0x2f, 0xe0, 0xfb, 0x5b,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0x68, 0xd5, 0x86, 0x7e, 0x03, 0x00, 0x00,
}
