// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type Response struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type MessageBody struct {
	Value                string                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Body                 map[string]*MessageBody `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MessageBody) Reset()         { *m = MessageBody{} }
func (m *MessageBody) String() string { return proto.CompactTextString(m) }
func (*MessageBody) ProtoMessage()    {}
func (*MessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{3}
}

func (m *MessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBody.Unmarshal(m, b)
}
func (m *MessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBody.Marshal(b, m, deterministic)
}
func (m *MessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBody.Merge(m, src)
}
func (m *MessageBody) XXX_Size() int {
	return xxx_messageInfo_MessageBody.Size(m)
}
func (m *MessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBody proto.InternalMessageInfo

func (m *MessageBody) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *MessageBody) GetBody() map[string]*MessageBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type Message struct {
	Sender               string                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	RoomID               string                  `protobuf:"bytes,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Labels               map[string]string       `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 map[string]*MessageBody `protobuf:"bytes,4,rep,name=body,proto3" json:"body,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UserState            map[string]*MessageBody `protobuf:"bytes,5,rep,name=userState,proto3" json:"userState,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Id                   string                  `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            string                  `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Message) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *Message) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Message) GetBody() map[string]*MessageBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetUserState() map[string]*MessageBody {
	if m != nil {
		return m.UserState
	}
	return nil
}

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type MessageResponse struct {
	Result               *Result    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Messages             []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{5}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *MessageResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "common.Result")
	proto.RegisterType((*EmptyRequest)(nil), "common.EmptyRequest")
	proto.RegisterType((*Response)(nil), "common.Response")
	proto.RegisterType((*MessageBody)(nil), "common.MessageBody")
	proto.RegisterMapType((map[string]*MessageBody)(nil), "common.MessageBody.BodyEntry")
	proto.RegisterType((*Message)(nil), "common.Message")
	proto.RegisterMapType((map[string]*MessageBody)(nil), "common.Message.BodyEntry")
	proto.RegisterMapType((map[string]string)(nil), "common.Message.LabelsEntry")
	proto.RegisterMapType((map[string]*MessageBody)(nil), "common.Message.UserStateEntry")
	proto.RegisterType((*MessageResponse)(nil), "common.MessageResponse")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6) }

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0x92, 0x36, 0x6d, 0xa6, 0xa8, 0x8b, 0x66, 0x57, 0xc8, 0x94, 0x1f, 0x55, 0x39, 0xa0,
	0x20, 0x44, 0x10, 0xdd, 0x0b, 0x20, 0x4e, 0x88, 0x3d, 0x20, 0x95, 0x03, 0x46, 0x3c, 0x40, 0x9a,
	0x0c, 0xa8, 0x22, 0x89, 0x83, 0xed, 0x20, 0xe5, 0x7d, 0x78, 0x35, 0xde, 0x03, 0xc5, 0x76, 0x76,
	0x43, 0xd4, 0x0b, 0x62, 0x2f, 0xad, 0xbf, 0x99, 0xf9, 0xe6, 0xfb, 0x66, 0xec, 0xc0, 0x79, 0x2e,
	0xaa, 0x4a, 0xd4, 0x2f, 0xec, 0x5f, 0xda, 0x48, 0xa1, 0x05, 0x86, 0x16, 0xc5, 0x7b, 0x08, 0x39,
	0xa9, 0xb6, 0xd4, 0xc8, 0x60, 0xa1, 0xda, 0x3c, 0x27, 0xa5, 0x98, 0xb7, 0xf5, 0x92, 0x25, 0x1f,
	0x20, 0x5e, 0xc0, 0x9c, 0xa4, 0x14, 0x92, 0xf9, 0x5b, 0x2f, 0x89, 0xb8, 0x05, 0x88, 0x30, 0xcb,
	0x45, 0x41, 0x2c, 0xd8, 0x7a, 0xc9, 0x9c, 0x9b, 0x73, 0xbc, 0x86, 0x3b, 0x57, 0x55, 0xa3, 0x3b,
	0x4e, 0x3f, 0x5a, 0x52, 0x3a, 0xde, 0xc1, 0x92, 0x93, 0x6a, 0x44, 0xad, 0x08, 0x9f, 0x40, 0x28,
	0x8d, 0x92, 0x69, 0xbf, 0xda, 0xad, 0x53, 0x67, 0xc8, 0xea, 0x73, 0x97, 0x8d, 0x7f, 0x79, 0xb0,
	0xfa, 0x48, 0x4a, 0x65, 0xdf, 0xe8, 0x9d, 0x28, 0xba, 0x5e, 0xfd, 0x67, 0x56, 0xb6, 0x64, 0x68,
	0x11, 0xb7, 0x00, 0x5f, 0xc2, 0xec, 0x20, 0x8a, 0x8e, 0xf9, 0xdb, 0x20, 0x59, 0xed, 0x1e, 0x0d,
	0xbd, 0x46, 0xc4, 0xb4, 0xff, 0xb9, 0xaa, 0xb5, 0xec, 0xb8, 0x29, 0xdd, 0xec, 0x21, 0xba, 0x0e,
	0xe1, 0x5d, 0x08, 0xbe, 0x53, 0xe7, 0x7a, 0xf6, 0x47, 0x7c, 0x3a, 0xe8, 0xf8, 0xc6, 0xde, 0xf9,
	0x89, 0x96, 0x4e, 0xfc, 0x8d, 0xff, 0xca, 0x8b, 0x7f, 0x07, 0xb0, 0x70, 0x29, 0xbc, 0x07, 0xa1,
	0xa2, 0xba, 0x20, 0xe9, 0xfa, 0x39, 0xd4, 0xc7, 0xa5, 0x10, 0xd5, 0x87, 0xf7, 0x6e, 0x73, 0x0e,
	0xe1, 0x25, 0x84, 0x65, 0x76, 0xa0, 0x52, 0xb1, 0xc0, 0xd8, 0x7f, 0x30, 0xd1, 0x4a, 0xf7, 0x26,
	0x6b, 0xcd, 0xbb, 0x52, 0x7c, 0xee, 0x26, 0x9e, 0x19, 0xca, 0xfd, 0x29, 0x65, 0x32, 0x2d, 0xbe,
	0x85, 0xa8, 0x55, 0x24, 0x3f, 0xeb, 0x4c, 0x13, 0x9b, 0x1b, 0xce, 0xe3, 0x29, 0xe7, 0xcb, 0x50,
	0x60, 0x89, 0x37, 0x04, 0x5c, 0x83, 0x7f, 0x2c, 0x58, 0x68, 0x5c, 0xfb, 0xc7, 0x02, 0x1f, 0x42,
	0xa4, 0x8f, 0x15, 0x29, 0x9d, 0x55, 0x0d, 0x5b, 0x98, 0xf0, 0x4d, 0x60, 0xf3, 0x1a, 0x56, 0x23,
	0xc7, 0x27, 0x76, 0x7b, 0x31, 0xde, 0x6d, 0x34, 0x5a, 0xe3, 0xed, 0x5e, 0xca, 0xe6, 0x13, 0xac,
	0xff, 0x9e, 0xe9, 0xff, 0xef, 0xf9, 0x2b, 0x9c, 0xb9, 0xcc, 0xbf, 0xbe, 0x64, 0x7c, 0x06, 0xcb,
	0xca, 0x52, 0x95, 0x7b, 0xa7, 0x67, 0x13, 0x31, 0x7e, 0x5d, 0x70, 0x08, 0xcd, 0x77, 0x79, 0xf9,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x60, 0xc3, 0x2b, 0xae, 0x03, 0x00, 0x00,
}
