// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatroom/receiver.proto

package chatroom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "gitlab.srgow.com/warehouse/proto/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendMessagesRequest struct {
	Messages             []*common.Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendMessagesRequest) Reset()         { *m = SendMessagesRequest{} }
func (m *SendMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessagesRequest) ProtoMessage()    {}
func (*SendMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_233896eee1eb079b, []int{0}
}

func (m *SendMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessagesRequest.Unmarshal(m, b)
}
func (m *SendMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessagesRequest.Marshal(b, m, deterministic)
}
func (m *SendMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessagesRequest.Merge(m, src)
}
func (m *SendMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessagesRequest.Size(m)
}
func (m *SendMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessagesRequest proto.InternalMessageInfo

func (m *SendMessagesRequest) GetMessages() []*common.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*SendMessagesRequest)(nil), "chatroom.SendMessagesRequest")
}

func init() { proto.RegisterFile("chatroom/receiver.proto", fileDescriptor_233896eee1eb079b) }

var fileDescriptor_233896eee1eb079b = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0xce, 0x48, 0x2c,
	0x29, 0xca, 0xcf, 0xcf, 0xd5, 0x2f, 0x4a, 0x4d, 0x4e, 0xcd, 0x2c, 0x4b, 0x2d, 0xd2, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x49, 0x48, 0x09, 0x27, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0xe9,
	0x43, 0x28, 0x88, 0xb4, 0x92, 0x13, 0x97, 0x70, 0x70, 0x6a, 0x5e, 0x8a, 0x6f, 0x6a, 0x71, 0x71,
	0x62, 0x7a, 0x6a, 0x71, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x36, 0x17, 0x47, 0x2e,
	0x54, 0x48, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x5f, 0x0f, 0xaa, 0x0f, 0xaa, 0x34, 0x08,
	0xae, 0xc0, 0x28, 0x82, 0x4b, 0x14, 0x26, 0x08, 0xb1, 0x3b, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39,
	0x55, 0xc8, 0x9e, 0x8b, 0x07, 0xd9, 0x70, 0x21, 0x59, 0x3d, 0x98, 0x63, 0xf4, 0xb0, 0x58, 0x2a,
	0x25, 0x00, 0xb3, 0x22, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x35, 0x89, 0x0d, 0xec, 0x48,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x76, 0x9c, 0xd8, 0xde, 0x00, 0x00, 0x00,
}
