// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatroom/room.proto

package chatroom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "gitlab.srgow.com/warehouse/proto/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRoomRequest struct {
	MemberNames          []string          `protobuf:"bytes,1,rep,name=memberNames,proto3" json:"memberNames,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a59c072ded4467, []int{0}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

func (m *CreateRoomRequest) GetMemberNames() []string {
	if m != nil {
		return m.MemberNames
	}
	return nil
}

func (m *CreateRoomRequest) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteRoomRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoomRequest) Reset()         { *m = DeleteRoomRequest{} }
func (m *DeleteRoomRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRoomRequest) ProtoMessage()    {}
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a59c072ded4467, []int{1}
}

func (m *DeleteRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoomRequest.Unmarshal(m, b)
}
func (m *DeleteRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoomRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoomRequest.Merge(m, src)
}
func (m *DeleteRoomRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRoomRequest.Size(m)
}
func (m *DeleteRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoomRequest proto.InternalMessageInfo

func (m *DeleteRoomRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateRoomResponse struct {
	Result               *common.Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Room                 *Room          `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateRoomResponse) Reset()         { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()    {}
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a59c072ded4467, []int{2}
}

func (m *CreateRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResponse.Unmarshal(m, b)
}
func (m *CreateRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResponse.Merge(m, src)
}
func (m *CreateRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResponse.Size(m)
}
func (m *CreateRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResponse proto.InternalMessageInfo

func (m *CreateRoomResponse) GetResult() *common.Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type AvailableRequest struct {
	MemberName           string   `protobuf:"bytes,1,opt,name=memberName,proto3" json:"memberName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableRequest) Reset()         { *m = AvailableRequest{} }
func (m *AvailableRequest) String() string { return proto.CompactTextString(m) }
func (*AvailableRequest) ProtoMessage()    {}
func (*AvailableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a59c072ded4467, []int{3}
}

func (m *AvailableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableRequest.Unmarshal(m, b)
}
func (m *AvailableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableRequest.Marshal(b, m, deterministic)
}
func (m *AvailableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableRequest.Merge(m, src)
}
func (m *AvailableRequest) XXX_Size() int {
	return xxx_messageInfo_AvailableRequest.Size(m)
}
func (m *AvailableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableRequest proto.InternalMessageInfo

func (m *AvailableRequest) GetMemberName() string {
	if m != nil {
		return m.MemberName
	}
	return ""
}

type Room struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberNames          []string          `protobuf:"bytes,2,rep,name=memberNames,proto3" json:"memberNames,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a59c072ded4467, []int{4}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetMemberNames() []string {
	if m != nil {
		return m.MemberNames
	}
	return nil
}

func (m *Room) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type RoomListResponse struct {
	Result               *common.Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Rooms                []*Room        `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomListResponse) Reset()         { *m = RoomListResponse{} }
func (m *RoomListResponse) String() string { return proto.CompactTextString(m) }
func (*RoomListResponse) ProtoMessage()    {}
func (*RoomListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a59c072ded4467, []int{5}
}

func (m *RoomListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomListResponse.Unmarshal(m, b)
}
func (m *RoomListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomListResponse.Marshal(b, m, deterministic)
}
func (m *RoomListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListResponse.Merge(m, src)
}
func (m *RoomListResponse) XXX_Size() int {
	return xxx_messageInfo_RoomListResponse.Size(m)
}
func (m *RoomListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListResponse proto.InternalMessageInfo

func (m *RoomListResponse) GetResult() *common.Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RoomListResponse) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRoomRequest)(nil), "chatroom.CreateRoomRequest")
	proto.RegisterMapType((map[string]string)(nil), "chatroom.CreateRoomRequest.DataEntry")
	proto.RegisterType((*DeleteRoomRequest)(nil), "chatroom.DeleteRoomRequest")
	proto.RegisterType((*CreateRoomResponse)(nil), "chatroom.CreateRoomResponse")
	proto.RegisterType((*AvailableRequest)(nil), "chatroom.AvailableRequest")
	proto.RegisterType((*Room)(nil), "chatroom.Room")
	proto.RegisterMapType((map[string]string)(nil), "chatroom.Room.DataEntry")
	proto.RegisterType((*RoomListResponse)(nil), "chatroom.RoomListResponse")
}

func init() { proto.RegisterFile("chatroom/room.proto", fileDescriptor_53a59c072ded4467) }

var fileDescriptor_53a59c072ded4467 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6b, 0xb3, 0x40,
	0x10, 0x46, 0x4d, 0xe4, 0x75, 0x84, 0x60, 0x36, 0xef, 0x41, 0x7c, 0x5f, 0x8a, 0xd8, 0x0f, 0x72,
	0x28, 0x06, 0xec, 0x21, 0x6d, 0x6f, 0x25, 0xe9, 0xad, 0xf4, 0x60, 0xff, 0x40, 0x36, 0xc9, 0x40,
	0xa5, 0x9a, 0x4d, 0x75, 0x13, 0xc8, 0xaf, 0xe9, 0xb9, 0xff, 0xa6, 0x3f, 0xa9, 0xec, 0xba, 0x26,
	0x6a, 0x4a, 0xa1, 0xd0, 0x8b, 0xba, 0xcf, 0x33, 0x33, 0xfb, 0xcc, 0x33, 0x23, 0x0c, 0x16, 0xcf,
	0x94, 0xe7, 0x8c, 0x65, 0x23, 0xf1, 0x08, 0xd7, 0x39, 0xe3, 0x8c, 0xfc, 0xa9, 0x40, 0x6f, 0xb0,
	0x60, 0x59, 0xc6, 0x56, 0xa3, 0xf2, 0x55, 0xd2, 0xc1, 0xbb, 0x06, 0xfd, 0x49, 0x8e, 0x94, 0x63,
	0xcc, 0x58, 0x16, 0xe3, 0xeb, 0x06, 0x0b, 0x4e, 0x7c, 0xb0, 0x33, 0xcc, 0xe6, 0x98, 0x3f, 0xd2,
	0x0c, 0x0b, 0x57, 0xf3, 0x8d, 0xa1, 0x15, 0xd7, 0x21, 0x72, 0x03, 0x9d, 0x25, 0xe5, 0xd4, 0xd5,
	0x7d, 0x63, 0x68, 0x47, 0xe7, 0x61, 0x75, 0x4b, 0x78, 0x54, 0x2c, 0x9c, 0x52, 0x4e, 0xef, 0x57,
	0x3c, 0xdf, 0xc5, 0x32, 0xc5, 0x1b, 0x83, 0xb5, 0x87, 0x88, 0x03, 0xc6, 0x0b, 0xee, 0x5c, 0xcd,
	0xd7, 0x86, 0x56, 0x2c, 0x3e, 0xc9, 0x5f, 0xe8, 0x6e, 0x69, 0xba, 0x41, 0x57, 0x97, 0x58, 0x79,
	0xb8, 0xd5, 0xaf, 0xb5, 0xe0, 0x14, 0xfa, 0x53, 0x4c, 0xb1, 0x29, 0xb5, 0x07, 0x7a, 0xb2, 0x54,
	0xf9, 0x7a, 0xb2, 0x0c, 0x66, 0x40, 0xea, 0x12, 0x8a, 0x35, 0x5b, 0x15, 0x48, 0x2e, 0xc0, 0xcc,
	0xb1, 0xd8, 0xa4, 0x5c, 0x46, 0xda, 0x51, 0x2f, 0x54, 0x2e, 0xc4, 0x12, 0x8d, 0x15, 0x4b, 0x02,
	0xe8, 0x88, 0x2e, 0xe4, 0xdd, 0x32, 0xaa, 0x6a, 0x4b, 0x56, 0x93, 0x5c, 0x10, 0x81, 0x73, 0xb7,
	0xa5, 0x49, 0x4a, 0xe7, 0x29, 0x56, 0x2a, 0x4e, 0x00, 0x0e, 0xee, 0x28, 0x35, 0x35, 0x24, 0x78,
	0xd3, 0xa0, 0x23, 0x4a, 0xb4, 0xe5, 0xb6, 0x9d, 0xd6, 0x8f, 0x9d, 0xbe, 0x54, 0x4e, 0x1b, 0xd2,
	0x69, 0xb7, 0x29, 0xe9, 0xf7, 0xcc, 0x9d, 0x81, 0x23, 0x0a, 0x3e, 0x24, 0x05, 0xff, 0xb1, 0x6b,
	0x67, 0xd0, 0x15, 0x8a, 0x0a, 0xb5, 0x0d, 0x6d, 0xdb, 0x4a, 0x32, 0xfa, 0xd0, 0xc0, 0x16, 0xe7,
	0x27, 0xcc, 0xb7, 0xc9, 0x02, 0xc9, 0x04, 0xcc, 0x72, 0x52, 0xe4, 0xdf, 0x37, 0xeb, 0xe3, 0xfd,
	0xff, 0x9a, 0x54, 0x12, 0x27, 0x60, 0xed, 0x87, 0x41, 0xbc, 0x43, 0x68, 0x7b, 0x42, 0x9e, 0xd7,
	0x14, 0xd5, 0xe8, 0x73, 0x0c, 0x66, 0xb9, 0x58, 0x75, 0x25, 0x47, 0xab, 0xe6, 0x39, 0xb5, 0xf6,
	0x65, 0xe2, 0xdc, 0x94, 0x3f, 0xd1, 0xd5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x84, 0x83,
	0x5b, 0x7a, 0x03, 0x00, 0x00,
}
