// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatroom/sender.proto

package chatroom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageReceiveRequest struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	ConsumeMessageIDs    []string `protobuf:"bytes,2,rep,name=consumeMessageIDs,proto3" json:"consumeMessageIDs,omitempty"`
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReceiveRequest) Reset()         { *m = MessageReceiveRequest{} }
func (m *MessageReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*MessageReceiveRequest) ProtoMessage()    {}
func (*MessageReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e945b3a5ecb3f56d, []int{0}
}

func (m *MessageReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReceiveRequest.Unmarshal(m, b)
}
func (m *MessageReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReceiveRequest.Marshal(b, m, deterministic)
}
func (m *MessageReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReceiveRequest.Merge(m, src)
}
func (m *MessageReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_MessageReceiveRequest.Size(m)
}
func (m *MessageReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReceiveRequest proto.InternalMessageInfo

func (m *MessageReceiveRequest) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *MessageReceiveRequest) GetConsumeMessageIDs() []string {
	if m != nil {
		return m.ConsumeMessageIDs
	}
	return nil
}

func (m *MessageReceiveRequest) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func init() {
	proto.RegisterType((*MessageReceiveRequest)(nil), "chatroom.MessageReceiveRequest")
}

func init() { proto.RegisterFile("chatroom/sender.proto", fileDescriptor_e945b3a5ecb3f56d) }

var fileDescriptor_e945b3a5ecb3f56d = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x6a, 0x84, 0x30,
	0x10, 0x86, 0xb1, 0x52, 0xd1, 0x5c, 0x4a, 0x53, 0x6c, 0xc5, 0x4b, 0xa5, 0x27, 0x0f, 0x25, 0x42,
	0xfb, 0x0a, 0x5e, 0xa4, 0xf4, 0x12, 0x9f, 0x20, 0x8d, 0x43, 0xd7, 0x43, 0x32, 0x6e, 0x26, 0x0a,
	0xbe, 0xfd, 0xc2, 0x1a, 0xbd, 0xec, 0x9e, 0x86, 0x7f, 0xbe, 0x19, 0xf8, 0x3f, 0x96, 0xeb, 0x93,
	0xf2, 0x0e, 0xd1, 0x34, 0x04, 0x76, 0x00, 0x27, 0x26, 0x87, 0x1e, 0x79, 0xba, 0xaf, 0xcb, 0x17,
	0x8d, 0xc6, 0xa0, 0x6d, 0xb6, 0xb1, 0xe1, 0x8f, 0x95, 0xe5, 0xbf, 0x40, 0xa4, 0xfe, 0x41, 0x82,
	0x86, 0x71, 0x01, 0x09, 0xe7, 0x19, 0xc8, 0xf3, 0x57, 0x96, 0x48, 0x44, 0xd3, 0xb5, 0x45, 0x54,
	0x45, 0x75, 0x26, 0x43, 0xe2, 0x9f, 0xec, 0x59, 0xa3, 0xa5, 0xd9, 0x40, 0xf8, 0xeb, 0x5a, 0x2a,
	0x1e, 0xaa, 0xb8, 0xce, 0xe4, 0x2d, 0xe0, 0x25, 0x4b, 0xb5, 0x9a, 0x94, 0x1e, 0xfd, 0x5a, 0xc4,
	0x55, 0x54, 0x3f, 0xca, 0x23, 0x7f, 0x29, 0xc6, 0xc3, 0x65, 0x0f, 0x76, 0xe8, 0xc1, 0x2d, 0xa3,
	0x06, 0xfe, 0xc3, 0x9e, 0x42, 0x93, 0x00, 0x89, 0xbf, 0x8b, 0xdd, 0x41, 0xdc, 0xed, 0x5a, 0xbe,
	0x89, 0xe0, 0x74, 0x60, 0x9a, 0xd0, 0x12, 0xfc, 0x25, 0x57, 0xc9, 0xef, 0x4b, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8e, 0x40, 0xda, 0x7d, 0x1c, 0x01, 0x00, 0x00,
}
