module.exports = {
    insert: 'INSERT INTO movielist SET ?',
    queryAll: 'SELECT * FROM movielist',
    queryByKind: 'SELECT * FROM movielist WHERE kind = ? limit ?, ?',
    updateByName: 'UPDATE movielist SET ? WHERE name = ?',
    queryHotEmoji: 'SELECT * FROM hotemoji',
    queryByName: 'SELECT * FROM movielist WHERE name LIKE ',
    queryLogin: 'SELECT * FROM users WHERE UserName=?',
    queryArticle: 'SELECT * FROM article order by id desc limit ?,?',
    queryId: 'SELECT count(id) AS count FROM users', //返回id总数
    queryCase: 'SELECT * FROM cases order by id desc limit ?,?',
    delUsers: 'DELETE FROM users WHERE Id=?',
    addUsers: 'INSERT INTO users (Id,ComTelephone,Password,UserName,CompanyId,IsAdmin) values (0,?,?,?,0,0)',
    putUsers: 'UPDATE users SET UserName=?,ComTelephone=?  WHERE Id=?',
    queryPass: 'SELECT Password FROM users WHERE UserName=?',
    putPass: 'UPDATE users SET Password=?  WHERE UserName=?',
    queryUsers: 'SELECT * FROM users order by id limit ?,?',
    delArticle: 'DELETE FROM article WHERE id=?',
    queryEssage: 'INSERT INTO article (id,title,tag,author,content,CreateTime,ArticleImg,see,chart,des) values (0,?,?,?,?,?,?,0,0,?)',
    artId: 'SELECT * FROM article WHERE id=?',
    caseId : 'SELECT * FROM cases WHERE id=?',
    addTable: 'INSERT INTO `?` (id, author, novelname, title) value (0, ?, ?, ?);',
    queryMap: 'select tablename from map where novelname like ',
    queryTable: 'select * from `?` ',
    addMap: 'INSERT INTO map (id, tablename, novelname) value (0, ?, ?);',
    creTable: 'create table `yuge`.`?` (`id` int unsigned not null auto_increment,author varchar(100) not null,novelname varchar(100) not null,title varchar(100) not null,PRIMARY KEY (`id`)) ENGINE = InnoDB CHARSET=utf8;'
};
